- _data/projects/hackedu/distraction_free_facebook_messenger.yml
* Club: hackEDU
* Name: Distraction Free Facebook Messenger
* Description: Eliminates all the distractions of Facebook Messenger.
* URL: https://chrome.google.com/webstore/detail/distraction-free-facebook/ipkbhlfkopeokhpbhgmlonagpppedfej
* GitHub: https://github.com/jonleung/distraction-free-facebook-messenger
* Authors:
* Jonathan Leung
:shipit:
> Add Distraction Free Facebook Messenger

- _data/projects/hackedu/ship_it.yml
* Club: hackEDU
* Name: Ship It
* Description: Utility website for generating pull requests to submit projects to https://shipped.hackedu.us.
* URL: https://shipit.hackedu.us
* GitHub: https://github.com/hackedu/shipit
* Authors:
* Zach Latta
:shipit:
> Add Ship It

- _data/projects/eshs_programming_club/build_your_own_lisp_-_gitbook.yml
* Club: ESHS Programming Club
* Name: Build Your Own Lisp - Gitbook
* Description: A port to gitbook of the ebook Build Your Own Lisp by Daniel Holden.
* URL: http://landersbenjamin.gitbooks.io/buildyourownlisp/
* GitHub: https://github.com/TheThirdOne/BuildYourOwnLispGitbook
* Authors:
* Benjamin Landers
* 
:shipit:
> Add Build Your Own Lisp - Gitbook

- _data/projects/eshs_programming_club/el_pinguino.yml
* Club: ESHS Programming Club
* Name: El Pinguino
* Description: El Pinguino lets you scrape Travelmob locations by country and convert to JSON.
* URL: https://github.com/HackerParadise2014/el_pinguino
* GitHub: https://github.com/HackerParadise2014/el_pinguino
* Authors:
* Max Wofford
* Rob Cole
:shipit:
> Add El Pinguino

- _data/projects/eshs_programming_club/shibesales.yml
* Club: ESHS Programming Club
* Name: ShibeSales
* Description: Miss a sale on Steam? Buy it for cheap with Dogecoin! At ShibeSales you can purchase Steam games on sale, and recommend games for us to keep on our watchlist.
* URL: http://shibesales.com/
* GitHub: https://github.com/MaxWofford/Shibe-Sales
* Authors:
* Max Wofford
:shipit:
> Add ShibeSales

- _data/projects/eshs_programming_club/dogevertising.yml
Add Dogevertising without newline in description.
> Add Dogevertising

- _data/projects/hacker_paradise/care_wall.yml
* Club: Hacker Paradise
* Name: Care Wall
* Description: Because sometimes we forget what we really care about.
* URL: http://careabout.herokuapp.com/
* GitHub: https://github.com/jonleung/Care
* Authors:
* Jon Leung
* Max Wofford
:shipit:
> Add Care Wall

- _includes/fork_banner.html
- _includes/header.html
- _sass/_layout.scss
This generally works, but the button gets covered by the "Fork me on GitHub" button if the window is too narrow. Any suggestions to fix that?
> add 'Add Project' link

- _data/projects/built_@_pennapps/ventib.yml
* Club: Built @ PennApps
* Name: Ventib
* Description: Ventib records all your speech, transcribes it, and sends it to a server for processing. Ventib's server then analyzes the data to provide statistics. Ventib also has a search function, which allows users to search through their past speech and obtain timestamped logs with location data.
* URL: http://github.com/cydrobolt/ventib
* GitHub: http://github.com/cydrobolt/ventib
* Authors:
* Chaoyi Zha
* Fox Wilson
* Samuel Damashek
:shipit:
> Add Ventib

- _data/projects/mca_programming_club/smart_sight.yml
* Club: MCA Programming Club
* Name: Smart Sight
* Description: An augmented reality real-time app that can identify products and the companies that produce them. It then displays the stock price along with other financial data of the company right on the camera screen in addition to providing a way to order the product that you see.
* GitHub: https://github.com/himat/SmartSight
* Authors:
* Hima Tammineedi
* Syed Raziq Mohideen
* Vivek Jain
* Anuraag Shankar
:shipit:
> Add Smart Sight

- _data/projects/hsmse,stuyvesant,trinity_club/leap_music.yml
* Club: HSMSE,Stuyvesant,Trinity Club
* Name: Leap Music
* Description: A Chrome Extension that uses the leap motion to controll pandora.
* GitHub: https://github.com/austincarvey/LeapMusic
* Authors:
* Austin Carvey
* Philip Steinman
* Grace Zhang
:shipit:
> Add Leap Music

- _data/projects/international_academy_east/tweetvr.yml
* Club: International Academy East
* Name: tweetVR
* Description: tweetVR augments tweets onto Google Maps Streetview for your Twitter viewing pleasure. Our targeted users are those who know there are infinite ways to view data. Users can view tweets, in virtual reality, in a radius of their current location or see what people are tweeting in a totally different hemisphere. Now what can be a better and faster way to discover what's trending around your current physical surroundings? :)
* URL: http://challengepost.com/software/tweetvr
* GitHub: https://github.com/gauss1181/MHacksV
* Authors:
* Shriyash Jalukar
* Megan Chen
* Nicole Flokos
* Sahil Panwar
:shipit:
> Add tweetVR

- _data/projects/elizabeth_high_school/handi-hacked.yml
* Club: Elizabeth High School
* Name: Handi-Hacked
* Description: Handi-hacked is a VR input device designed to make virtual reality easily accessible for all. Such a device allows the joys of VR to be simple and intuitive for all handicapped people, as the input device supports a plethora of wheelchairs (motorized or not). Furthermore, it is also a great tool for therapies, VR enthusiasts, or one who may have interest in life bound to a wheelchair.
* URL: http://hackgeny.challengepost.com/submissions/32141-handi-hacked
* GitHub: https://github.com/raphaelrk/CatDaddy
* Authors:
* Amy Sorto
* Raphael Kats
* Tim Lupo
* Kaushik Mahadevan
* Ari Berkowicz
:shipit:
> Add Handi-Hacked

- _data/projects/mundelein_high_school/datawave.yml
* Club: Mundelein High School
* Name: DataWave
* Description: Internet over FM radio waves. Plug the attachment into your android or computer audio jack and have an internet connection for miles
* GitHub: https://github.com/datawaveteam
* Authors:
* Raphael Rouvinov
* Stefan Aleksic
* Esperat Hounyo
* Matt Kula
* Peter Szczepanski
:shipit:
> Add DataWave

- _data/projects/townsend_harris_high_school/myobserver.yml
* Club: Townsend Harris High School
* Name: MyObserver
* Description: MyObserver is an iOS app that allows users to interact with Google Street View using Google Cardboard. The user can also zoom in and out using a Myo device.
* URL: http://challengepost.com/software/myobserver
* GitHub: https://github.com/jackcook/myobserver
* Authors:
* Jack Cook, Tim Hung, Vicki Long, Ibnat Iqbal, Neil Chen
:shipit:
> Add MyObserver

- _data/projects/elizabeth_high_school/pearl_runner.yml
* Club: Elizabeth High School
* Name: Pearl Runner
* Description: Too often, sexual education is dismissed as taboo in our culture. Through Pearl Runner, a young girl discovers the value of sexual health and safety by collecting condoms and avoiding the plague of STDs that are infecting her life. Inspired by stories of young girls overcoming sexual harassment, teenage pregnancy, and other consequences of poor sexual education, we strove to create a welcoming environment for users of all ages to learn and break down the walls of sexual taboo.
* URL: http://challengepost.com/software/pearl-runner-hk22c
* GitHub: https://github.com/sharon-lin/PearlHacks
* Authors:
* Amy Sorto
* Karla Rodriguez
* Sharon Lin
* Adina Walzer
* Silvia Jaramillo
:shipit:
> Add Pearl Runner

- _data/projects/austin_high_school/anonymous_warning.yml
* Club: Austin High School
* Name: Anonymous Warning
* Description: This application allows you to Anonymously Message your friends.
* URL: http://mahahahajan.github.io/AnonWarning/
* GitHub: https://github.com/mahahahajan/AnonWarning
* Authors:
* Pulkit Mahajan, Gisela Kottmeier
:shipit:
> Add Anonymous Warning

- _data/projects/glenaeon_rudolf_steiner_school/esoteric_adventures.yml
* Club: Glenaeon Rudolf Steiner School
* Name: Esoteric Adventures
* Description: Esoteric adventures is a game where you battle against the corporations in order to save your forest and furthermore the world from being put under the power of the right wing. #LD48
* URL: http://harrisonshoebridge.me/esoteric-adventures
* GitHub: https://github.com/paked/esoteric-adventures
* Authors:
* Harrison Shoebridge
* Rafe Skidmore
* Sam Finch
:shipit:
> Add Esoteric Adventures

- _data/projects/zrlify.yml
* Clubs:
* Glenaeon Rudolf Steiner School
* Name: zrlify
* Description: Make any website look like that of Zach Latta's with this click to use chrome extension!
* URL: https://chrome.google.com/webstore/detail/zrlify/mpokfjeacmbjhldahgmoanmhddidgfio
* GitHub: https://github.com/paked/zrlify
* Authors:
* Harrison Shoebridge
:shipit:
> Add zrlify

- _data/projects/elisha_coad's_portfolio.yml
This replaces #98 by touching up the `.yml` file and adding the proper school name :-).
> projects: add Elisha Coad's Portfolio
